Repository jenkins-x/jx-git-operator, pull requests merged in 2021-01, with the labels that each got.

#101 chore: fix PR pipeline
  .lighthouse/jenkins-x/pullrequest.yaml
  OWNERS
Labels: size/S

#100 feat: added in oci registry secret so we can boot from secure OCI chart registries with helmfile
  charts/jx-git-operator/templates/oci-registry-secrets.yaml
  charts/jx-git-operator/values.yaml
Labels: approved, ok-to-test, size/S

#121 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#122 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#123 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#126 feat: added in optional secret we can mount to boot jobs as env vars
  charts/jx-git-operator/templates/job-secret.yaml
  charts/jx-git-operator/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#131 fix: fixed error in chart secret template
  charts/jx-git-operator/templates/job-secret.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#132 fix: ensured secret is always present just with empty data so we can rely on it to be present to bind to other resources
  charts/jx-git-operator/templates/job-secret.yaml
  charts/jx-git-operator/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#138 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot
